/* @author Flavio Luiz Bé & Felipe Busch*/
package tela;

import apoio.Formatacao;
import apoio.Validacao;
import dao.ClientesDAO;
import entidade.Clientes;
import java.awt.Color;
import javax.swing.JOptionPane;

public class IfrClientes extends javax.swing.JInternalFrame {

    int varID = 0;

    public IfrClientes() {
        initComponents();

        Formatacao.formatarCep(tffCadCep);
        Formatacao.formatarCpf(tffCadCpf);
        Formatacao.formatarCnpj(tffCadCnpj);
        Formatacao.formatarTelefone(tffCadTelefone);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFechar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        abaCadastro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfdCadNome = new javax.swing.JTextField();
        tfdCadEmail = new javax.swing.JTextField();
        tfdCadEndereco = new javax.swing.JTextField();
        tfdCadNumero = new javax.swing.JTextField();
        tffCadCpf = new javax.swing.JFormattedTextField();
        tffCadCnpj = new javax.swing.JFormattedTextField();
        tffCadTelefone = new javax.swing.JFormattedTextField();
        cbxCadStatus = new javax.swing.JComboBox<>();
        tfdCadComplemento = new javax.swing.JTextField();
        tfdCadBairro = new javax.swing.JTextField();
        tfdCadCidade = new javax.swing.JTextField();
        tffCadCep = new javax.swing.JFormattedTextField();
        abaConsulta = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        tfdConsultar = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        spnConsulta = new javax.swing.JScrollPane();
        tblConsulta = new javax.swing.JTable();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setTitle("Cadastro de Clientes");

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("E-mail:");

        jLabel3.setText("CPF:");

        jLabel4.setText("CNPJ:");

        jLabel5.setText("Telefone:");

        jLabel6.setText("Status");

        jLabel7.setText("Endereço:");

        jLabel8.setText("Número:");

        jLabel9.setText("Complem.:");

        jLabel10.setText("Bairro:");

        jLabel11.setText("Cidade:");

        jLabel12.setText("CEP:");

        tfdCadNumero.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfdCadNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfdCadNumeroKeyTyped(evt);
            }
        });

        tffCadCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tffCadCpfFocusLost(evt);
            }
        });

        tffCadCnpj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tffCadCnpjFocusLost(evt);
            }
        });

        cbxCadStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo" }));
        cbxCadStatus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCadStatusItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout abaCadastroLayout = new javax.swing.GroupLayout(abaCadastro);
        abaCadastro.setLayout(abaCadastroLayout);
        abaCadastroLayout.setHorizontalGroup(
            abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaCadastroLayout.createSequentialGroup()
                        .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(abaCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(abaCadastroLayout.createSequentialGroup()
                                        .addComponent(tffCadCep, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(tffCadCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfdCadComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(abaCadastroLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfdCadBairro))
                                    .addGroup(abaCadastroLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(tffCadCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(abaCadastroLayout.createSequentialGroup()
                                        .addComponent(tffCadTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxCadStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfdCadCidade)))
                            .addGroup(abaCadastroLayout.createSequentialGroup()
                                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(abaCadastroLayout.createSequentialGroup()
                                        .addComponent(tfdCadEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
                                        .addGap(58, 58, 58)
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfdCadNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfdCadNome)
                                    .addComponent(tfdCadEmail))))
                        .addGap(14, 14, 14))
                    .addGroup(abaCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addContainerGap())))
        );
        abaCadastroLayout.setVerticalGroup(
            abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfdCadNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfdCadEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfdCadEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(tfdCadNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfdCadComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(tfdCadBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(tfdCadCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(tffCadCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(tffCadCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(tffCadTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(cbxCadStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(tffCadCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro", abaCadastro);

        jLabel13.setText("Busca");

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        tblConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Email", "Endereço", "Número", "Complemento", "Bairro", "Cidade", "CEP", "CPF", "CNPJ", "Telefone", "Status"
            }
        ));
        spnConsulta.setViewportView(tblConsulta);

        javax.swing.GroupLayout abaConsultaLayout = new javax.swing.GroupLayout(abaConsulta);
        abaConsulta.setLayout(abaConsultaLayout);
        abaConsultaLayout.setHorizontalGroup(
            abaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(tfdConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 966, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(abaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(abaConsultaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(spnConsulta)
                    .addContainerGap()))
        );
        abaConsultaLayout.setVerticalGroup(
            abaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaConsultaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(abaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar)
                    .addComponent(jLabel13))
                .addContainerGap(191, Short.MAX_VALUE))
            .addGroup(abaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(abaConsultaLayout.createSequentialGroup()
                    .addGap(51, 51, 51)
                    .addComponent(spnConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Consulta", abaConsulta);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnFechar))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        new ClientesDAO().popularTabela(tblConsulta, tfdConsultar.getText());
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (tblConsulta.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um Registro na Tabela Consulta!");
        } else {
            String idTabela = String.valueOf(tblConsulta.getValueAt(tblConsulta.getSelectedRow(), 0));
            varID = Integer.parseInt(idTabela);
            if (new ClientesDAO().excluir(varID) == null) {
                JOptionPane.showMessageDialog(this, "Registro Excluído com Sucesso!");
                new ClientesDAO().popularTabela(tblConsulta, tfdConsultar.getText());
            } else {
                JOptionPane.showMessageDialog(this, "Problema ao excluir o Registro!");
            }
            varID = 0;
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void cbxCadStatusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCadStatusItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCadStatusItemStateChanged

    private void tfdCadNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdCadNumeroKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_tfdCadNumeroKeyTyped

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (tfdCadNome.getText().length() > 0
                && tfdCadEmail.getText().length() > 0
                && tfdCadEndereco.getText().length() > 0
                && tfdCadNumero.getText().length() > 0
                && tfdCadBairro.getText().length() > 0
                && tfdCadCidade.getText().length() > 0
                && tffCadCep.getText().length() > 0
                && tffCadTelefone.getText().length() > 0) {

            Clientes cliente = new Clientes();

            cliente.setId(varID);
            cliente.setNome(tfdCadNome.getText());
            cliente.setEmail(tfdCadEmail.getText());
            cliente.setEndereco(tfdCadEndereco.getText());
            cliente.setNumero(tfdCadNumero.getText());
            cliente.setComplemento(tfdCadComplemento.getText());
            cliente.setBairro(tfdCadBairro.getText());
            cliente.setCidade(tfdCadCidade.getText());
            cliente.setCep(tffCadCep.getText());
            cliente.setTelefone(tffCadTelefone.getText());
            if (String.valueOf(tffCadCpf.getText().substring(0, 1)).equals(" ")) {
                cliente.setCpf(null);
            } else {
                cliente.setCpf(tffCadCpf.getText());
            }
            if (String.valueOf(tffCadCnpj.getText().substring(0, 1)).equals(" ")) {
                cliente.setCnpj(null);
            } else {
                cliente.setCnpj(tffCadCnpj.getText());
            }
            if (String.valueOf(cbxCadStatus.getSelectedItem()).equals("Ativo")) {
                cliente.setStatus("a");
            } else {
                cliente.setStatus("i");
            }

            ClientesDAO clienteDAO = new ClientesDAO();
            if (varID == 0) {
                if (clienteDAO.salvar(cliente) == null) {
                    tfdCadNome.setText("");
                    tfdCadEmail.setText("");
                    tfdCadEndereco.setText("");
                    tfdCadNumero.setText("");
                    tfdCadComplemento.setText("");
                    tfdCadBairro.setText("");
                    tfdCadCidade.setText("");
                    tffCadCep.setText("");
                    tffCadCpf.setText("");
                    tffCadCnpj.setText("");
                    tffCadTelefone.setText("");
                    cbxCadStatus.setSelectedItem("Ativo");

                    JOptionPane.showMessageDialog(this, "Registro salvo com sucesso!");
                    tfdCadNome.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(this, "Problemas ao salvar registro!");
                }
            } else {
                if (clienteDAO.atualizar(cliente) == null) {
                    tfdCadNome.setText("");
                    tfdCadEmail.setText("");
                    tfdCadEndereco.setText("");
                    tfdCadNumero.setText("");
                    tfdCadComplemento.setText("");
                    tfdCadBairro.setText("");
                    tfdCadCidade.setText("");
                    tffCadCep.setText("");
                    tffCadCpf.setText("");
                    tffCadCnpj.setText("");
                    tffCadTelefone.setText("");
                    cbxCadStatus.setSelectedItem("Ativo");

                    JOptionPane.showMessageDialog(this, "Registro alterado com sucesso!");
                    tfdCadNome.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(this, "Problemas ao alterar registro!");
                }
            }
            varID = 0;
        } else {
            JOptionPane.showMessageDialog(this, "Favor preencher todos os campos!");
            tfdCadNome.requestFocus();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (tblConsulta.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um Registro na Tabela Consulta!");
        } else {
            String idTabela = String.valueOf(tblConsulta.getValueAt(tblConsulta.getSelectedRow(), 0));
            varID = Integer.parseInt(idTabela);

            Clientes cliente = new ClientesDAO().consultarId(varID);
            if (cliente != null) {
                jTabbedPane1.setSelectedIndex(0);
                tfdCadNome.setText(cliente.getNome());
                tfdCadEmail.setText(cliente.getEmail());
                tfdCadEndereco.setText(cliente.getEndereco());
                tfdCadNumero.setText(cliente.getNumero());
                tfdCadComplemento.setText(cliente.getComplemento());
                tfdCadBairro.setText(cliente.getBairro());
                tfdCadCidade.setText(cliente.getCidade());
                tffCadCep.setText(cliente.getCep());
                tffCadCpf.setText(cliente.getCpf());
                tffCadCnpj.setText(cliente.getCnpj());
                tffCadTelefone.setText(cliente.getTelefone());
                if (cliente.getStatus().equals("a")) {
                    cbxCadStatus.setSelectedItem("Ativo");
                } else {
                    cbxCadStatus.setSelectedItem("Inativo");
                }
                tfdCadNome.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Código do cliente não encontrado!");
            }
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void tffCadCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tffCadCpfFocusLost
        if (!Validacao.validarCPF(Formatacao.removerFormatacao(tffCadCpf.getText()))) {
            tffCadCpf.setBackground(Color.YELLOW);
        } else {
            tffCadCpf.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_tffCadCpfFocusLost

    private void tffCadCnpjFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tffCadCnpjFocusLost
        if (!Validacao.validarCNPJ(Formatacao.removerFormatacao(tffCadCnpj.getText()))) {
            tffCadCnpj.setBackground(Color.YELLOW);
        } else {
            tffCadCnpj.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_tffCadCnpjFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abaCadastro;
    private javax.swing.JPanel abaConsulta;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbxCadStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JScrollPane spnConsulta;
    private javax.swing.JTable tblConsulta;
    private javax.swing.JTextField tfdCadBairro;
    private javax.swing.JTextField tfdCadCidade;
    private javax.swing.JTextField tfdCadComplemento;
    private javax.swing.JTextField tfdCadEmail;
    private javax.swing.JTextField tfdCadEndereco;
    private javax.swing.JTextField tfdCadNome;
    private javax.swing.JTextField tfdCadNumero;
    private javax.swing.JTextField tfdConsultar;
    private javax.swing.JFormattedTextField tffCadCep;
    private javax.swing.JFormattedTextField tffCadCnpj;
    private javax.swing.JFormattedTextField tffCadCpf;
    private javax.swing.JFormattedTextField tffCadTelefone;
    // End of variables declaration//GEN-END:variables
}
