/* @author Flavio Luiz Bé & Felipe Busch*/
package tela;

public class FrmPrincipal extends javax.swing.JFrame {

    public FrmPrincipal() {
        initComponents();
        setTitle("Sistema de Prestação de Serviços");
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastros = new javax.swing.JMenu();
        cadClientes = new javax.swing.JMenuItem();
        cadFornecedores = new javax.swing.JMenuItem();
        cadServicos = new javax.swing.JMenuItem();
        cadMateriais = new javax.swing.JMenuItem();
        menuCompras = new javax.swing.JMenu();
        comprasCompras = new javax.swing.JMenuItem();
        menuOrcamentos = new javax.swing.JMenu();
        orcamOrcamentos = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        ajudaSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1069, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );

        menuCadastros.setText("Cadastros");

        cadClientes.setText("Clientes");
        cadClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadClientesActionPerformed(evt);
            }
        });
        menuCadastros.add(cadClientes);

        cadFornecedores.setText("Fornecedores");
        cadFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadFornecedoresActionPerformed(evt);
            }
        });
        menuCadastros.add(cadFornecedores);

        cadServicos.setText("Serviços");
        cadServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadServicosActionPerformed(evt);
            }
        });
        menuCadastros.add(cadServicos);

        cadMateriais.setText("Materiais");
        cadMateriais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadMateriaisActionPerformed(evt);
            }
        });
        menuCadastros.add(cadMateriais);

        jMenuBar1.add(menuCadastros);

        menuCompras.setText("Compras");

        comprasCompras.setText("Compras");
        comprasCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprasComprasActionPerformed(evt);
            }
        });
        menuCompras.add(comprasCompras);

        jMenuBar1.add(menuCompras);

        menuOrcamentos.setText("Orçamentos");

        orcamOrcamentos.setText("Orçamentos");
        orcamOrcamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orcamOrcamentosActionPerformed(evt);
            }
        });
        menuOrcamentos.add(orcamOrcamentos);

        jMenuBar1.add(menuOrcamentos);

        menuAjuda.setText("Ajuda");

        ajudaSair.setText("Sair");
        ajudaSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajudaSairActionPerformed(evt);
            }
        });
        menuAjuda.add(ajudaSair);

        jMenuBar1.add(menuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajudaSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajudaSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ajudaSairActionPerformed

    private void cadClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadClientesActionPerformed
        IfrClientes ifrClientes = new IfrClientes();
        jDesktopPane1.add(ifrClientes);
        ifrClientes.setVisible(true);
    }//GEN-LAST:event_cadClientesActionPerformed

    private void cadFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadFornecedoresActionPerformed
        IfrFornecedores ifrFornecedores = new IfrFornecedores();
        jDesktopPane1.add(ifrFornecedores);
        ifrFornecedores.setVisible(true);
    }//GEN-LAST:event_cadFornecedoresActionPerformed

    private void cadServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadServicosActionPerformed
        IfrServicos ifrServicos = new IfrServicos();
        jDesktopPane1.add(ifrServicos);
        ifrServicos.setVisible(true);
    }//GEN-LAST:event_cadServicosActionPerformed

    private void cadMateriaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadMateriaisActionPerformed
        IfrMateriais ifrMateriais = new IfrMateriais();
        jDesktopPane1.add(ifrMateriais);
        ifrMateriais.setVisible(true);
    }//GEN-LAST:event_cadMateriaisActionPerformed

    private void comprasComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprasComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comprasComprasActionPerformed

    private void orcamOrcamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orcamOrcamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orcamOrcamentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ajudaSair;
    private javax.swing.JMenuItem cadClientes;
    private javax.swing.JMenuItem cadFornecedores;
    private javax.swing.JMenuItem cadMateriais;
    private javax.swing.JMenuItem cadServicos;
    private javax.swing.JMenuItem comprasCompras;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenu menuCompras;
    private javax.swing.JMenu menuOrcamentos;
    private javax.swing.JMenuItem orcamOrcamentos;
    // End of variables declaration//GEN-END:variables
}
